version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: swiper
    versions:
    - 6.4.10
    - 6.4.11
    - 6.4.15
    - 6.4.8
    - 6.5.0
    - 6.5.6
    - 6.5.7
  - dependency-name: stickybits
    versions:
    - 3.7.8
  - dependency-name: next-offline
    versions:
    - 5.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
